lang: "ru"

# jekyll-seo-tag
title: Yücel Toluyağ
author: Yücel Toluyağ
description: Linux,Yazılım & Ortaya Karışık
logo: /assets/img/logo.png
social:
  links:
    - https://github.com/yuceltoluyag
webmaster_verifications:
  # google: 1234
  #yandex: xx

google_analytics:
#ya_metrika: 49475860

repo_url: https://github.com/yuceltoluyag/yuceltoluyag.github.io

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%d.%m.%Y"     # see http://shopify.github.io/liquid/filters/date/
paginate: 8                 # use "layout: paginate" in the index.html to enable pagination

# Theme settings
hide_title: true            # remove site heading in the header
hide_footer: false           # hide the "previous" and "next" links at the end of each post
dark_theme: true            # use the dark mode as default
dark_header: false           # keep the header dark
dark_footer: true           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header. / & _pages
  - Anasayfa: /
  - about.md
  - tags.md
  - archive.md
  # - README.md
  # - Telegram: https://t.me/yuceltoluyag       # linking external sites is also supported

icons:                      # icons in the header, see http://fontawesome.com/icons
  linux: https://yuceltoluyag.github.io
  telegram-plane: https://t.me/yuceltoluyag
  youtube: https://www.youtube.com/channel/UCJyK4D5BcoPXjV5T8N8-liA?sub_confirmation=1
  github: https://github.com/yuceltoluyag
  twitter: https://twitter.com/Friday13Jv
  rss: /feed.xml
  # envelope: "mailto:ytoluyag@gmail.com"

tag_page: "/tags/"

include: ["_pages"]

comments:
  disqus: "adamcoder"

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji
